### ISSUE TITLE
?????

### ISSUE THREAD

**Issue by crazyshark2** [odoo-turkey/integration#45]

**Comment by crazyshark2** [comment]
?

**Comment by crazyshark2** [comment]
16 için güncelliyecek bir baba yiğit aranıyormuş

**Comment by aaltinisik** [comment]
Onları da sen eklemeyi denemelisin

**Comment by crazyshark2** [comment]
Bende yeniyim kodlama bilsem yazıp koyarım sıkıntı yok ama bilmediğim için maalesef :( Ama teşekkür ederim ilginiz için

**Comment by aaltinisik** [comment]
Anne bana süt getir!

öğren, yaz, koy, millete iş buyurma 
GitHub yan gelip yatma yeri değil 
Selamlar

**Comment by crazyshark2** [comment]
Millete iş buyurmuş olsam buraya gördüğüm eksiklikleri yazmaz sizin gibi bi hesap açıp içine bişiler koyup sizin gibi üzerine ekleyenlerin gelmesini beklemeyi düşünürdüm.
Teşekkür ederim.

**Comment by aaltinisik** [comment]
Tuzağımızı görmüş, büyük oyunu çözmüşsün. Sana bi havadisim var buranın düzeni böyle. 

Free as in free speech not as in free beer!

Öğren, yaz, koy, millete iş buyurma.
Parasını vermediğin insanlara şu eksikleri ne zaman yapacaksınız diye sormak iş buyurma olur.
Bu konuda uyarınca saldırıya geçmek de cabası. 
Sen de koy bişeyleri sonra sen de pusuya yat.
